apiVersion: v1
kind: Service
metadata:
  name: nexus-api
  namespace: nexus
  labels:
    app: nexus-api
    app.kubernetes.io/name: nexus
spec:
  type: ClusterIP
  selector:
    app: nexus-api
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
