apiVersion: v1
kind: Service
metadata:
  name: nexus-web
  namespace: nexus
  labels:
    app: nexus-web
    app.kubernetes.io/name: nexus
spec:
  type: ClusterIP
  selector:
    app: nexus-web
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
